server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8066

dropboxConfig:
  appName: CloudSyncIosrProject
  appKey: nlsu5a4n7jcr3il
  appKeySecret: c1tufi0cm9vjoh0

onedriveConfig:
  appName: burak
  appKey: 000000004015302A
  appKeySecret: 3nbUeQnDqrFLSZwPKpjLBrYubFelq7TL
